# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.api_v1_top_fund import ApiV1TopFund

class TestApiV1TopFund(unittest.TestCase):
    """ApiV1TopFund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1TopFund:
        """Test ApiV1TopFund
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1TopFund`
        """
        model = ApiV1TopFund()
        if include_optional:
            return ApiV1TopFund(
                cik = '',
                name = '',
                period_of_report = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                pnl = 1.337
            )
        else:
            return ApiV1TopFund(
        )
        """

    def testApiV1TopFund(self):
        """Test ApiV1TopFund"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
