# coding: utf-8

"""
    SEC form 13F API

    API for SEC form filings such as 13F.

    The version of the OpenAPI document: 1.0.0
    Contact: forms13f@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from forms13f.models.api_v1_holders_get200_response import ApiV1HoldersGet200Response

class TestApiV1HoldersGet200Response(unittest.TestCase):
    """ApiV1HoldersGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1HoldersGet200Response:
        """Test ApiV1HoldersGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1HoldersGet200Response`
        """
        model = ApiV1HoldersGet200Response()
        if include_optional:
            return ApiV1HoldersGet200Response(
                cusip = '',
                period_of_report = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                ciks = [
                    ''
                    ]
            )
        else:
            return ApiV1HoldersGet200Response(
        )
        """

    def testApiV1HoldersGet200Response(self):
        """Test ApiV1HoldersGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
