/*
SEC form 13F API

API for SEC form filings such as 13F.

API version: 1.0.0
Contact: forms13f@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forms13f

import (
	"encoding/json"
)

// checks if the ApiV1HoldersGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1HoldersGet200Response{}

// ApiV1HoldersGet200Response struct for ApiV1HoldersGet200Response
type ApiV1HoldersGet200Response struct {
	// The CUSIP of the securities.
	Cusip *string `json:"cusip,omitempty"`
	// The period of report date.
	PeriodOfReport *string `json:"period_of_report,omitempty"`
	// An array of CIKs.
	Ciks []string `json:"ciks,omitempty"`
}

// NewApiV1HoldersGet200Response instantiates a new ApiV1HoldersGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1HoldersGet200Response() *ApiV1HoldersGet200Response {
	this := ApiV1HoldersGet200Response{}
	return &this
}

// NewApiV1HoldersGet200ResponseWithDefaults instantiates a new ApiV1HoldersGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1HoldersGet200ResponseWithDefaults() *ApiV1HoldersGet200Response {
	this := ApiV1HoldersGet200Response{}
	return &this
}

// GetCusip returns the Cusip field value if set, zero value otherwise.
func (o *ApiV1HoldersGet200Response) GetCusip() string {
	if o == nil || IsNil(o.Cusip) {
		var ret string
		return ret
	}
	return *o.Cusip
}

// GetCusipOk returns a tuple with the Cusip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1HoldersGet200Response) GetCusipOk() (*string, bool) {
	if o == nil || IsNil(o.Cusip) {
		return nil, false
	}
	return o.Cusip, true
}

// HasCusip returns a boolean if a field has been set.
func (o *ApiV1HoldersGet200Response) HasCusip() bool {
	if o != nil && !IsNil(o.Cusip) {
		return true
	}

	return false
}

// SetCusip gets a reference to the given string and assigns it to the Cusip field.
func (o *ApiV1HoldersGet200Response) SetCusip(v string) {
	o.Cusip = &v
}

// GetPeriodOfReport returns the PeriodOfReport field value if set, zero value otherwise.
func (o *ApiV1HoldersGet200Response) GetPeriodOfReport() string {
	if o == nil || IsNil(o.PeriodOfReport) {
		var ret string
		return ret
	}
	return *o.PeriodOfReport
}

// GetPeriodOfReportOk returns a tuple with the PeriodOfReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1HoldersGet200Response) GetPeriodOfReportOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodOfReport) {
		return nil, false
	}
	return o.PeriodOfReport, true
}

// HasPeriodOfReport returns a boolean if a field has been set.
func (o *ApiV1HoldersGet200Response) HasPeriodOfReport() bool {
	if o != nil && !IsNil(o.PeriodOfReport) {
		return true
	}

	return false
}

// SetPeriodOfReport gets a reference to the given string and assigns it to the PeriodOfReport field.
func (o *ApiV1HoldersGet200Response) SetPeriodOfReport(v string) {
	o.PeriodOfReport = &v
}

// GetCiks returns the Ciks field value if set, zero value otherwise.
func (o *ApiV1HoldersGet200Response) GetCiks() []string {
	if o == nil || IsNil(o.Ciks) {
		var ret []string
		return ret
	}
	return o.Ciks
}

// GetCiksOk returns a tuple with the Ciks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1HoldersGet200Response) GetCiksOk() ([]string, bool) {
	if o == nil || IsNil(o.Ciks) {
		return nil, false
	}
	return o.Ciks, true
}

// HasCiks returns a boolean if a field has been set.
func (o *ApiV1HoldersGet200Response) HasCiks() bool {
	if o != nil && !IsNil(o.Ciks) {
		return true
	}

	return false
}

// SetCiks gets a reference to the given []string and assigns it to the Ciks field.
func (o *ApiV1HoldersGet200Response) SetCiks(v []string) {
	o.Ciks = v
}

func (o ApiV1HoldersGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1HoldersGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cusip) {
		toSerialize["cusip"] = o.Cusip
	}
	if !IsNil(o.PeriodOfReport) {
		toSerialize["period_of_report"] = o.PeriodOfReport
	}
	if !IsNil(o.Ciks) {
		toSerialize["ciks"] = o.Ciks
	}
	return toSerialize, nil
}

type NullableApiV1HoldersGet200Response struct {
	value *ApiV1HoldersGet200Response
	isSet bool
}

func (v NullableApiV1HoldersGet200Response) Get() *ApiV1HoldersGet200Response {
	return v.value
}

func (v *NullableApiV1HoldersGet200Response) Set(val *ApiV1HoldersGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1HoldersGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1HoldersGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1HoldersGet200Response(val *ApiV1HoldersGet200Response) *NullableApiV1HoldersGet200Response {
	return &NullableApiV1HoldersGet200Response{value: val, isSet: true}
}

func (v NullableApiV1HoldersGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1HoldersGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


