/*
SEC form 13F API

API for SEC form filings such as 13F.

API version: 1.0.0
Contact: forms13f@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forms13f

import (
	"encoding/json"
)

// checks if the ApiV1TopFund type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1TopFund{}

// ApiV1TopFund struct for ApiV1TopFund
type ApiV1TopFund struct {
	// The Central Index Key (CIK) of the fund.
	Cik *string `json:"cik,omitempty"`
	// The name of the fund.
	Name *string `json:"name,omitempty"`
	// The period of report date (end of quarter).
	PeriodOfReport *string `json:"period_of_report,omitempty"`
	// The portfolio PnL percentage for the given quarter.
	Pnl NullableFloat64 `json:"pnl,omitempty"`
}

// NewApiV1TopFund instantiates a new ApiV1TopFund object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1TopFund() *ApiV1TopFund {
	this := ApiV1TopFund{}
	return &this
}

// NewApiV1TopFundWithDefaults instantiates a new ApiV1TopFund object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1TopFundWithDefaults() *ApiV1TopFund {
	this := ApiV1TopFund{}
	return &this
}

// GetCik returns the Cik field value if set, zero value otherwise.
func (o *ApiV1TopFund) GetCik() string {
	if o == nil || IsNil(o.Cik) {
		var ret string
		return ret
	}
	return *o.Cik
}

// GetCikOk returns a tuple with the Cik field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1TopFund) GetCikOk() (*string, bool) {
	if o == nil || IsNil(o.Cik) {
		return nil, false
	}
	return o.Cik, true
}

// HasCik returns a boolean if a field has been set.
func (o *ApiV1TopFund) HasCik() bool {
	if o != nil && !IsNil(o.Cik) {
		return true
	}

	return false
}

// SetCik gets a reference to the given string and assigns it to the Cik field.
func (o *ApiV1TopFund) SetCik(v string) {
	o.Cik = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiV1TopFund) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1TopFund) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiV1TopFund) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiV1TopFund) SetName(v string) {
	o.Name = &v
}

// GetPeriodOfReport returns the PeriodOfReport field value if set, zero value otherwise.
func (o *ApiV1TopFund) GetPeriodOfReport() string {
	if o == nil || IsNil(o.PeriodOfReport) {
		var ret string
		return ret
	}
	return *o.PeriodOfReport
}

// GetPeriodOfReportOk returns a tuple with the PeriodOfReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1TopFund) GetPeriodOfReportOk() (*string, bool) {
	if o == nil || IsNil(o.PeriodOfReport) {
		return nil, false
	}
	return o.PeriodOfReport, true
}

// HasPeriodOfReport returns a boolean if a field has been set.
func (o *ApiV1TopFund) HasPeriodOfReport() bool {
	if o != nil && !IsNil(o.PeriodOfReport) {
		return true
	}

	return false
}

// SetPeriodOfReport gets a reference to the given string and assigns it to the PeriodOfReport field.
func (o *ApiV1TopFund) SetPeriodOfReport(v string) {
	o.PeriodOfReport = &v
}

// GetPnl returns the Pnl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiV1TopFund) GetPnl() float64 {
	if o == nil || IsNil(o.Pnl.Get()) {
		var ret float64
		return ret
	}
	return *o.Pnl.Get()
}

// GetPnlOk returns a tuple with the Pnl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiV1TopFund) GetPnlOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pnl.Get(), o.Pnl.IsSet()
}

// HasPnl returns a boolean if a field has been set.
func (o *ApiV1TopFund) HasPnl() bool {
	if o != nil && o.Pnl.IsSet() {
		return true
	}

	return false
}

// SetPnl gets a reference to the given NullableFloat64 and assigns it to the Pnl field.
func (o *ApiV1TopFund) SetPnl(v float64) {
	o.Pnl.Set(&v)
}
// SetPnlNil sets the value for Pnl to be an explicit nil
func (o *ApiV1TopFund) SetPnlNil() {
	o.Pnl.Set(nil)
}

// UnsetPnl ensures that no value is present for Pnl, not even an explicit nil
func (o *ApiV1TopFund) UnsetPnl() {
	o.Pnl.Unset()
}

func (o ApiV1TopFund) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1TopFund) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cik) {
		toSerialize["cik"] = o.Cik
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PeriodOfReport) {
		toSerialize["period_of_report"] = o.PeriodOfReport
	}
	if o.Pnl.IsSet() {
		toSerialize["pnl"] = o.Pnl.Get()
	}
	return toSerialize, nil
}

type NullableApiV1TopFund struct {
	value *ApiV1TopFund
	isSet bool
}

func (v NullableApiV1TopFund) Get() *ApiV1TopFund {
	return v.value
}

func (v *NullableApiV1TopFund) Set(val *ApiV1TopFund) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1TopFund) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1TopFund) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1TopFund(val *ApiV1TopFund) *NullableApiV1TopFund {
	return &NullableApiV1TopFund{value: val, isSet: true}
}

func (v NullableApiV1TopFund) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1TopFund) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


