/*
SEC form 13F API

API for SEC form filings such as 13F.

API version: 1.0.0
Contact: forms13f@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package forms13f

import (
	"encoding/json"
)

// checks if the ApiV1FormResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1FormResponse{}

// ApiV1FormResponse struct for ApiV1FormResponse
type ApiV1FormResponse struct {
	// Estimated total PnL percentage across all holdings in the form since the period of report.
	TotalPnl NullableFloat64 `json:"total_pnl,omitempty"`
	// The holdings reported in the form.
	Entries []ApiV1FormEntry `json:"entries,omitempty"`
}

// NewApiV1FormResponse instantiates a new ApiV1FormResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1FormResponse() *ApiV1FormResponse {
	this := ApiV1FormResponse{}
	return &this
}

// NewApiV1FormResponseWithDefaults instantiates a new ApiV1FormResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1FormResponseWithDefaults() *ApiV1FormResponse {
	this := ApiV1FormResponse{}
	return &this
}

// GetTotalPnl returns the TotalPnl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiV1FormResponse) GetTotalPnl() float64 {
	if o == nil || IsNil(o.TotalPnl.Get()) {
		var ret float64
		return ret
	}
	return *o.TotalPnl.Get()
}

// GetTotalPnlOk returns a tuple with the TotalPnl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiV1FormResponse) GetTotalPnlOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalPnl.Get(), o.TotalPnl.IsSet()
}

// HasTotalPnl returns a boolean if a field has been set.
func (o *ApiV1FormResponse) HasTotalPnl() bool {
	if o != nil && o.TotalPnl.IsSet() {
		return true
	}

	return false
}

// SetTotalPnl gets a reference to the given NullableFloat64 and assigns it to the TotalPnl field.
func (o *ApiV1FormResponse) SetTotalPnl(v float64) {
	o.TotalPnl.Set(&v)
}
// SetTotalPnlNil sets the value for TotalPnl to be an explicit nil
func (o *ApiV1FormResponse) SetTotalPnlNil() {
	o.TotalPnl.Set(nil)
}

// UnsetTotalPnl ensures that no value is present for TotalPnl, not even an explicit nil
func (o *ApiV1FormResponse) UnsetTotalPnl() {
	o.TotalPnl.Unset()
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *ApiV1FormResponse) GetEntries() []ApiV1FormEntry {
	if o == nil || IsNil(o.Entries) {
		var ret []ApiV1FormEntry
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1FormResponse) GetEntriesOk() ([]ApiV1FormEntry, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *ApiV1FormResponse) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []ApiV1FormEntry and assigns it to the Entries field.
func (o *ApiV1FormResponse) SetEntries(v []ApiV1FormEntry) {
	o.Entries = v
}

func (o ApiV1FormResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1FormResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TotalPnl.IsSet() {
		toSerialize["total_pnl"] = o.TotalPnl.Get()
	}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	return toSerialize, nil
}

type NullableApiV1FormResponse struct {
	value *ApiV1FormResponse
	isSet bool
}

func (v NullableApiV1FormResponse) Get() *ApiV1FormResponse {
	return v.value
}

func (v *NullableApiV1FormResponse) Set(val *ApiV1FormResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1FormResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1FormResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1FormResponse(val *ApiV1FormResponse) *NullableApiV1FormResponse {
	return &NullableApiV1FormResponse{value: val, isSet: true}
}

func (v NullableApiV1FormResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1FormResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


